version: '3'
services:
  seq:
    image: datalust/seq:latest
    ports:
      - '80:80'
      - '5341:5341'
    environment:
      ACCEPT_EULA: Y

  postgres:
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=demouser
      - POSTGRES_PASSWORD=demopassword
      - POSTGRES_DB=demodatabase
    image: postgres

  sqlserver:
    ports:
      - '1433:1433'
    volumes:
      - sql1data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=demo01!password
      - MSSQL_PID=Developer
    image: microsoft/mssql-server-linux

  web:
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - 'DATABASETYPE=SqlServer'
      - 'CONNECTIONSTRING=Serversqlserver;User ID=sa;Database=demodatabase;Password=demo01!password'
      - 'SERILOG__WRITETO__0__NAME=LiterateConsole'
      - 'SERILOG__WRITETO__1__NAME=Seq'
      - 'SERILOG__WRITETO__1__ARGS__SERVERURL=http://seq:5341'
    links:
      - 'postgres:postgres'
      - 'seq:seq'
    ports:
      - '5000:80'

volumes:
  sql1data:
